import sys
import os
import ctypes
import json
import time

# Prevent this file (sdl2.py) from self-importing instead of the real 'sdl2' package
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir in sys.path:
    sys.path.remove(current_dir)
import sdl2
sys.path.insert(0, current_dir)

# Read the FFB JSON array generated by the AI
file = open("output.txt", "r")
variables = file.read()
file.close()

def play_effects():
    # Initialize SDL2 haptic and joystick subsystems
    if sdl2.SDL_Init(sdl2.SDL_INIT_JOYSTICK | sdl2.SDL_INIT_HAPTIC) < 0:
        print(f"SDL Init failed: {sdl2.SDL_GetError().decode('utf-8')}")
        return

    # Check for connected devices
    num_haptics = sdl2.SDL_NumHaptics()
    if num_haptics <= 0:
        print("No haptic/FFB steering wheel detected by SDL2.")
        sdl2.SDL_Quit()
        return

    # Open the first haptic device
    haptic = sdl2.SDL_HapticOpen(0)
    if not haptic:
        print(f"Failed to open haptic device: {sdl2.SDL_GetError().decode('utf-8')}")
        sdl2.SDL_Quit()
        return

    print(f"Successfully opened haptic device: {sdl2.SDL_HapticName(0).decode('utf-8')}")

    try:
        effects_data = json.loads(variables)
    except json.JSONDecodeError as e:
        print(f"Failed to parse JSON from output.txt: {e}")
        sdl2.SDL_HapticClose(haptic)
        sdl2.SDL_Quit()
        return

    effect_ids = []

    for data in effects_data:
        effect = sdl2.SDL_HapticEffect()
        effect_type = data.get("effect_type")

        # 1. Constant force mapping
        if effect_type == "constant":
            effect.type = sdl2.SDL_HAPTIC_CONSTANT
            effect.constant.direction.type = sdl2.SDL_HAPTIC_CARTESIAN
            dir_vector = data.get("direction", [1, 0, 0])
            for i, val in enumerate(dir_vector[:3]):
                effect.constant.direction.dir[i] = val
            effect.constant.length = sdl2.SDL_HAPTIC_INFINITY if data.get("length") == 4294967295 else data.get("length", 1000)
            effect.constant.level = data.get("level", 10000)
            effect.constant.delay = data.get("delay", 0)

        # 2. Periodic wave mapping (sine, triangle, sawtooth)
        elif effect_type == "periodic":
            wave = data.get("wave_type", "sine")
            if wave == "sine":
                effect.type = sdl2.SDL_HAPTIC_SINE
            elif wave == "triangle":
                effect.type = sdl2.SDL_HAPTIC_TRIANGLE
            elif wave == "sawtooth_up":
                effect.type = sdl2.SDL_HAPTIC_SAWTOOTHUP
            elif wave == "sawtooth_down":
                effect.type = sdl2.SDL_HAPTIC_SAWTOOTHDOWN

            effect.periodic.direction.type = sdl2.SDL_HAPTIC_CARTESIAN
            dir_vector = data.get("direction", [1, 0, 0])
            for i, val in enumerate(dir_vector[:3]):
                effect.periodic.direction.dir[i] = val
            effect.periodic.length = sdl2.SDL_HAPTIC_INFINITY if data.get("length") == 4294967295 else data.get("length", 1000)
            effect.periodic.period = data.get("period", 100)
            effect.periodic.magnitude = data.get("magnitude", 5000)
            effect.periodic.delay = data.get("delay", 0)

        # 3. Condition mapping (friction, damper, spring, inertia)
        elif effect_type == "condition":
            cond = data.get("condition_type", "spring")
            if cond in ["spring", "centering_spring"]:
                effect.type = sdl2.SDL_HAPTIC_SPRING
            elif cond == "damper":
                effect.type = sdl2.SDL_HAPTIC_DAMPER
            elif cond in ["friction", "natural_friction"]:
                effect.type = sdl2.SDL_HAPTIC_FRICTION
            elif cond == "inertia":
                effect.type = sdl2.SDL_HAPTIC_INERTIA

            effect.condition.length = sdl2.SDL_HAPTIC_INFINITY if data.get("length") == 4294967295 else data.get("length", 1000)
            effect.condition.delay = data.get("delay", 0)
            
            # Map parameters to the primary axis (index 0)
            effect.condition.right_coeff[0] = data.get("right_coeff", 5000)
            effect.condition.left_coeff[0] = data.get("left_coeff", 5000)
            effect.condition.deadband[0] = data.get("deadband", 0)
            effect.condition.center[0] = data.get("center", 0)
            effect.condition.right_sat[0] = 32767
            effect.condition.left_sat[0] = 32767

        else:
            print(f"Skipping unsupported effect type: {effect_type}")
            continue

        # Upload the haptic effect structure to the device
        eff_id = sdl2.SDL_HapticNewEffect(haptic, ctypes.byref(effect))
        if eff_id < 0:
            print(f"Failed to upload effect: {sdl2.SDL_GetError().decode('utf-8')}")
        else:
            effect_ids.append(eff_id)
            print(f"Uploaded {effect_type} effect (ID: {eff_id})")

    # Play all uploaded effects
    for eff_id in effect_ids:
        sdl2.SDL_HapticRunEffect(haptic, eff_id, 1)

    print("Effects are running! Press Ctrl+C to stop.")
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping effects and exiting...")
    finally:
        # Destroy and cleanup haptic effects
        for eff_id in effect_ids:
            sdl2.SDL_HapticDestroyEffect(haptic, eff_id)
        sdl2.SDL_HapticClose(haptic)
        sdl2.SDL_Quit()

if __name__ == "__main__":
    play_effects()